[project]
name = "pkg"
version = "0.1.0"
description = "Mind Palace"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
addopts = "--ignore=_milvus -v"
testpaths = [
  "pkg"
]
