CREATE TABLE IF NOT EXISTS tag(
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS memory_tag(
  tag_id INTEGER NOT NULL,
  memory_id uuid NOT NULL,
  PRIMARY KEY(memory_id, tag_id),
  FOREIGN KEY(memory_id) REFERENCES memory(id) ON DELETE CASCADE,
  FOREIGN KEY(tag_id) REFERENCES tag(id) ON DELETE CASCADE
);
