name: Test Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.9']
        go-version: ['1.22']

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Golang ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Python project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make deps-py

    - name: Install Go project dependencies
      run: |
        make deps-go

    - name: Compile protocol buffers
      run: |
        make clean-rpc
        make rpc

    - name: Run tests
      run: |
        make test
