name: Test Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [python]
        python-version: ['3.9']

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: Set up ptyhon ${{ matrix.python-version }}
      if: matrix.language == 'python'
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Run Python tests
      if: matrix.language == 'python'
      run: |
        pytest
